version: '3'
services:
  app_1:
    image: codemindrohan/cust_nginx:v7
    ports:
    - "81:80"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.swarm-worker2==true
